"""Add DoneTicket table

Revision ID: 170e12b39ea0
Revises: 7783cef4e914
Create Date: 2025-10-30 11:21:35.374079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170e12b39ea0'
down_revision = '7783cef4e914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['submitted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
