"""add image data columns

Revision ID: 6420fd8705c8
Revises: a80382a9392d
Create Date: 2025-11-13 13:50:47.027785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6420fd8705c8'
down_revision = 'a80382a9392d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('done_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['submitted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('photo_data')

    with op.batch_alter_table('done_ticket', schema=None) as batch_op:
        batch_op.drop_column('photo_data')

    # ### end Alembic commands ###
