"""Add first_name and last_name to User

Revision ID: 77642ea6586a
Revises: 22283c93dec0
Create Date: 2025-10-28 19:10:19.123810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77642ea6586a'
down_revision = '22283c93dec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['submitted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
