"""Add Ticket table

Revision ID: 7783cef4e914
Revises: ffe4ad7e5d62
Create Date: 2025-10-29 09:40:23.789809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7783cef4e914'
down_revision = 'ffe4ad7e5d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_name', sa.String(length=150), nullable=False),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('submitted_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_submitted', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.drop_table('ticket')
    # ### end Alembic commands ###
