"""add photo column to Ticket and DoneTicket

Revision ID: a80382a9392d
Revises: 35eef7e86984
Create Date: 2025-11-12 10:41:05.349198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80382a9392d'
down_revision = '35eef7e86984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('done_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['submitted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('photo')

    with op.batch_alter_table('done_ticket', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
