"""Added date_submitted to Request

Revision ID: ffe4ad7e5d62
Revises: b1c014f7a94c
Create Date: 2025-10-28 20:32:41.847192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe4ad7e5d62'
down_revision = 'b1c014f7a94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_submitted', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['submitted_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('date_submitted')

    # ### end Alembic commands ###
